global using Microsoft.EntityFrameworkCore;
global using Multiple_Layered_DataAccess.Library.Data;
global using Multiple_Layered_DataAccess.Library.IdentityConfigurations;
global using Multiple_Layered_DataAccess.Library.Seeds;